import js from "@eslint/js";
import reactHooks from "eslint-plugin-react-hooks";
import tseslint from "typescript-eslint";

// `eslint-plugin-react-hooks` exposes its rules through different keys
// depending on the major version, so resolve them defensively.
const reactHooksRecommended =
  reactHooks.configs["recommended-latest"] ?? reactHooks.configs.recommended;

export default tseslint.config(
  {
    ignores: [
      "dist/**",
      "coverage/**",
      "node_modules/**",
      "__mocks__/**",
      "example/**",
      // Generated by scripts/postbuild.mjs.
      "core.js",
      "core.d.ts",
      // Auto-generated from src/icons (scripts/generate-icons.mjs).
      "src/icons/registry.ts",
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    // Config files and build scripts run in Node, not in the app.
    files: ["*.js"],
    languageOptions: {
      sourceType: "commonjs",
      globals: {
        module: "writable",
        require: "readonly",
        console: "readonly",
        process: "readonly",
        __dirname: "readonly",
      },
    },
  },
  {
    files: ["scripts/**/*.mjs"],
    languageOptions: {
      sourceType: "module",
      globals: { console: "readonly", process: "readonly" },
    },
  },
  {
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        // React Native provides these globals at runtime.
        console: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        require: "readonly",
        global: "readonly",
        process: "readonly",
      },
    },
    plugins: { "react-hooks": reactHooks },
    rules: {
      ...(reactHooksRecommended?.rules ?? {}),
      // `any` is used deliberately where STIX content is dynamic.
      "@typescript-eslint/no-explicit-any": "off",
      // The graph core is a close port of the OASIS STIX visualisation engine
      // and keeps its `let`-based style, so `prefer-const` is not enforced.
      "prefer-const": "off",
      "@typescript-eslint/no-unused-vars": [
        "warn",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
    },
  }
);
