/**
 * Post-build steps for the published bundle.
 *
 * The published build is CommonJS on purpose: React Native's Metro bundler,
 * webpack and Vite all consume it, while an ESM build could not be honest here
 * anyway — the STIX icons are Metro assets (`require("./x.png")`), which no
 * Node ESM loader can resolve (`@arethetypeswrong/cli` reports exactly that).
 * TypeScript source is on GitHub for anyone who wants to read it.
 *
 * 1. `tsc` only emits JavaScript, so the icon assets referenced by
 *    `dist/icons/registry.js` are copied next to the code that requires them.
 *    Only the files the registry actually references are copied — directory
 *    copies have a habit of shipping `index.ts` and `*.test.ts` too.
 *
 * 2. Guards: every referenced icon must exist after the copy, and no
 *    TypeScript source may end up in `dist/`. Both would otherwise only show up
 *    as a blank node icon, or as stray sources in the tarball.
 *
 * 3. Subpath shims. `stix2vis-native/core` is exposed through the `exports`
 *    map, which Node 10-era resolution and Metro runs with
 *    `unstable_enablePackageExports: false` cannot see. A one-line `core.js`
 *    (and its `.d.ts`) at the package root makes the same import work
 *    everywhere, without a bundler-specific workaround.
 */
import {
  copyFileSync,
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const sourceIconDir = join(root, "src", "icons");
const publishedIconDir = join(root, "dist", "icons");

if (!existsSync(publishedIconDir))
  mkdirSync(publishedIconDir, { recursive: true });

const registry = readFileSync(join(publishedIconDir, "registry.js"), "utf8");
const referenced = [
  ...new Set(
    [...registry.matchAll(/["']\.\/([^"']+)["']/g)].map((match) => match[1])
  ),
];

if (referenced.length === 0)
  throw new Error(
    "dist/icons/registry.js references no icons — did the generator change?"
  );

for (const file of referenced) {
  const source = join(sourceIconDir, String(file));

  if (!existsSync(source))
    throw new Error(
      `dist/icons/registry.js references "${file}", which is not in ` +
        "src/icons. Run `npm run icons` to regenerate the registry."
    );

  copyFileSync(source, join(publishedIconDir, String(file)));
}

/** Fails the build if TypeScript source leaked into the published output. */
function assertNoSources(dir) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const path = join(dir, entry.name);

    if (entry.isDirectory()) {
      assertNoSources(path);
      continue;
    }

    if (/\.(ts|tsx)$/.test(entry.name) && !entry.name.endsWith(".d.ts"))
      throw new Error(
        `${relative(root, path)} is TypeScript source and must not be ` +
          "published. Copy assets explicitly rather than whole directories."
      );
  }
}

assertNoSources(join(root, "dist"));

writeFileSync(
  join(root, "core.js"),
  "// Generated by scripts/postbuild.mjs — subpath shim for stix2vis-native/core.\n" +
    'module.exports = require("./dist/core/index.js");\n',
  "utf8"
);

writeFileSync(
  join(root, "core.d.ts"),
  "// Generated by scripts/postbuild.mjs — subpath shim for stix2vis-native/core.\n" +
    'export * from "./dist/core/index";\n',
  "utf8"
);

console.log(
  `Postbuild complete: ${referenced.length} icons copied and verified, ` +
    "subpath shims written."
);
